CREATE USER 'queue'@'%' IDENTIFIED BY 'queue';
CREATE USER 'bot'@'%' IDENTIFIED BY 'bot';
GRANT USAGE ON *.* TO 'queue'@'%';
GRANT USAGE ON *.* TO 'bot'@'%';
ALTER USER 'queue'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
ALTER USER 'bot'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;